                                  ##Secondary Server - docker-compose.yml

services:
  apache2:
    image: httpd:latest
    container_name: apache2
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs/

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /home/ubuntu/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
