scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.31.12.29:9100']

  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']
rule_files:
  - "alert.yml"
